###############################################################################
# Created by write_sdc
# Mon Jul  4 13:56:56 2022
###############################################################################
current_design cbx_1__2_
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name prog_clk_0_S_in -period 10.0000 [get_ports {prog_clk_0_S_in}]
set_clock_transition 0.1500 [get_clocks {prog_clk_0_S_in}]
set_clock_uncertainty 0.2500 prog_clk_0_S_in
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {IO_ISOL_N}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {SC_IN_BOT}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {SC_IN_TOP}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {bottom_width_0_height_0__pin_0_}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {ccff_head}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_in[0]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_in[10]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_in[11]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_in[12]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_in[13]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_in[14]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_in[15]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_in[16]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_in[17]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_in[18]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_in[19]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_in[1]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_in[2]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_in[3]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_in[4]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_in[5]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_in[6]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_in[7]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_in[8]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_in[9]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_in[0]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_in[10]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_in[11]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_in[12]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_in[13]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_in[14]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_in[15]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_in[16]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_in[17]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_in[18]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_in[19]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_in[1]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_in[2]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_in[3]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_in[4]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_in[5]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_in[6]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_in[7]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_in[8]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_in[9]}]
set_input_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {gfpga_pad_EMBEDDED_IO_HD_SOC_IN}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {SC_OUT_BOT}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {SC_OUT_TOP}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {bottom_grid_pin_0_}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {bottom_grid_pin_10_}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {bottom_grid_pin_11_}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {bottom_grid_pin_12_}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {bottom_grid_pin_13_}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {bottom_grid_pin_14_}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {bottom_grid_pin_15_}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {bottom_grid_pin_1_}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {bottom_grid_pin_2_}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {bottom_grid_pin_3_}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {bottom_grid_pin_4_}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {bottom_grid_pin_5_}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {bottom_grid_pin_6_}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {bottom_grid_pin_7_}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {bottom_grid_pin_8_}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {bottom_grid_pin_9_}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {bottom_width_0_height_0__pin_1_lower}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {bottom_width_0_height_0__pin_1_upper}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {ccff_tail}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_out[0]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_out[10]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_out[11]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_out[12]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_out[13]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_out[14]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_out[15]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_out[16]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_out[17]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_out[18]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_out[19]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_out[1]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_out[2]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_out[3]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_out[4]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_out[5]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_out[6]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_out[7]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_out[8]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_left_out[9]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_out[0]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_out[10]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_out[11]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_out[12]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_out[13]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_out[14]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_out[15]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_out[16]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_out[17]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_out[18]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_out[19]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_out[1]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_out[2]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_out[3]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_out[4]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_out[5]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_out[6]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_out[7]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_out[8]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {chanx_right_out[9]}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {gfpga_pad_EMBEDDED_IO_HD_SOC_DIR}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {gfpga_pad_EMBEDDED_IO_HD_SOC_OUT}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {prog_clk_0_W_out}]
set_output_delay 2.0000 -clock [get_clocks {prog_clk_0_S_in}] -add_delay [get_ports {top_grid_pin_0_}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {SC_OUT_BOT}]
set_load -pin_load 0.0334 [get_ports {SC_OUT_TOP}]
set_load -pin_load 0.0334 [get_ports {bottom_grid_pin_0_}]
set_load -pin_load 0.0334 [get_ports {bottom_grid_pin_10_}]
set_load -pin_load 0.0334 [get_ports {bottom_grid_pin_11_}]
set_load -pin_load 0.0334 [get_ports {bottom_grid_pin_12_}]
set_load -pin_load 0.0334 [get_ports {bottom_grid_pin_13_}]
set_load -pin_load 0.0334 [get_ports {bottom_grid_pin_14_}]
set_load -pin_load 0.0334 [get_ports {bottom_grid_pin_15_}]
set_load -pin_load 0.0334 [get_ports {bottom_grid_pin_1_}]
set_load -pin_load 0.0334 [get_ports {bottom_grid_pin_2_}]
set_load -pin_load 0.0334 [get_ports {bottom_grid_pin_3_}]
set_load -pin_load 0.0334 [get_ports {bottom_grid_pin_4_}]
set_load -pin_load 0.0334 [get_ports {bottom_grid_pin_5_}]
set_load -pin_load 0.0334 [get_ports {bottom_grid_pin_6_}]
set_load -pin_load 0.0334 [get_ports {bottom_grid_pin_7_}]
set_load -pin_load 0.0334 [get_ports {bottom_grid_pin_8_}]
set_load -pin_load 0.0334 [get_ports {bottom_grid_pin_9_}]
set_load -pin_load 0.0334 [get_ports {bottom_width_0_height_0__pin_1_lower}]
set_load -pin_load 0.0334 [get_ports {bottom_width_0_height_0__pin_1_upper}]
set_load -pin_load 0.0334 [get_ports {ccff_tail}]
set_load -pin_load 0.0334 [get_ports {gfpga_pad_EMBEDDED_IO_HD_SOC_DIR}]
set_load -pin_load 0.0334 [get_ports {gfpga_pad_EMBEDDED_IO_HD_SOC_OUT}]
set_load -pin_load 0.0334 [get_ports {prog_clk_0_W_out}]
set_load -pin_load 0.0334 [get_ports {top_grid_pin_0_}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[19]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[18]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[17]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[16]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[15]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[14]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[13]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[12]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[11]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[10]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[9]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[8]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[7]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[6]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[5]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[4]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[3]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[2]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[1]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[0]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[19]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[18]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[17]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[16]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[15]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[14]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[13]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[12]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[11]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[10]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[9]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[8]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[7]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[6]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[5]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[4]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[3]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[2]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[1]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {IO_ISOL_N}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SC_IN_BOT}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SC_IN_TOP}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {bottom_width_0_height_0__pin_0_}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ccff_head}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gfpga_pad_EMBEDDED_IO_HD_SOC_IN}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {prog_clk_0_S_in}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[0]}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_fanout 5.0000 [current_design]
